---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yada
  labels:
    app: yada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yada
  template:
    metadata:
      labels:
        app: yada
    spec:
      containers:
        - name: yada
          image: sylvanld/yada:${DEPLOYED_VERSION}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: yada
spec:
  selector:
    app: yada
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: yada
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: yada.tmsstudio.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: yada
              servicePort: 80

